### ISSUE TITLE
搜索，release pdf

### ISSUE THREAD

**Issue by zsqw123** [kotlin-book-cn/kotlin-book-cn.github.io#1]
1. 希望可以支持 book 内容的搜索
2. 希望 pdf 不是直接塞在 git 里面，这样其实仓库会变得很大，建议每一个版本之后可以发布一个 GitHub release

Thanks！

**Comment by hltj** [comment]
> 1. 希望可以支持 book 内容的搜索
> 2. 希望 pdf 不是直接塞在 git 里面，这样其实仓库会变得很大，建议每一个版本之后可以发布一个 GitHub release
> 
> Thanks！

没办法支持搜索，因为内容太多了，超过了 honkit 支持的最大内容量。
pdf 放 github release 国内可能下载困难。目前放在版本库里解决方案是只保留一个 commit。
